import os

# ENTER BOT TOKEN (Get your BOT_TOKEN by talking to @botfather)
BOT_TOKEN = os.getenv("BOT_TOKEN")
GDRIVE_FOLDER_ID = os.getenv("GDRIVE_FOLDER_ID")
OWNER_ID = int(os.getenv("OWNER_ID"))
DOWNLOAD_DIR = "/app/downloads"
DOWNLOAD_STATUS_UPDATE_INTERVAL = 5
AUTO_DELETE_MESSAGE_DURATION = 20
IS_TEAM_DRIVE = None
INDEX_URL = os.getenv("INDEX_URL")
USER_SESSION_STRING = os.getenv("USER_SESSION_STRING")
TELEGRAM_API = int(os.getenv("TELEGRAM_API"))
TELEGRAM_HASH = os.getenv("TELEGRAM_HASH")
USE_SERVICE_ACCOUNTS = None
MEGA_API_KEY = os.getenv("MEGA_API_KEY")
MEGA_EMAIL_ID = os.getenv("MEGA_EMAIL_ID")
MEGA_PASSWORD = os.getenv("MEGA_PASSWORD")
